[package]
name = "app2"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = {version="0.4" ,features=["clock"]}
chrono-tz="0.10"

[[bin]]
name="date1"
path="src/DateProps1.rs"

[[bin]]
name="date2"
path="src/DateProps2.rs"

[[bin]]
name="conversion"
path="src/ConversionFns.rs"

[[bin]]
name="array"
path="src/Arrays1.rs"

[[bin]]
name="array2"
path="src/Arrays2.rs"

[[bin]]
name="tuples"
path="src/Tuples1.rs"

[[bin]]
name="vectors1"
path="src/Vectors1.rs"

[[bin]]
name="vectors2"
path="src/Vectors2.rs"

[[bin]]
name="vectors3"
path="src/Vectors3.rs"

[[bin]]
name="linkedlist"
path="src/LinkedListDemos.rs"

[[bin]]
name="rcdemos"
path="src/RCDemos.rs"

[[bin]]
name="struct2"
path="src/Struct2.rs"

[[bin]]
name="struct3"
path="src/Struct3.rs"