[package]
name = "app2"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = {version="0.4" ,features=["clock"]}
chrono-tz="0.10"

[[bin]]
name="date1"
path="src/DateProps1.rs"

[[bin]]
name="date2"
path="src/DateProps2.rs"

[[bin]]
name="conversion"
path="src/ConversionFns.rs"

[[bin]]
name="array"
path="src/Arrays1.rs"

[[bin]]
name="array2"
path="src/Arrays2.rs"

[[bin]]
name="tuples"
path="src/Tuples1.rs"

[[bin]]
name="vectors1"
path="src/Vectors1.rs"

[[bin]]
name="vectors2"
path="src/Vectors2.rs"

[[bin]]
name="vectors3"
path="src/Vectors3.rs"

[[bin]]
name="linkedlist"
path="src/LinkedListDemos.rs"

[[bin]]
name="rcdemos"
path="src/RCDemos.rs"

[[bin]]
name="struct2"
path="src/Struct2.rs"

[[bin]]
name="struct3"
path="src/Struct3.rs"

[[bin]]
name="enums1"
path="src/Enums1.rs"


[[bin]]
name="enums2"
path="src/Enums2.rs"

[[bin]]
name="trait1"
path="src/Trait1.rs"

[[bin]]
name="generic"
path="src/Generics.rs"

[[bin]]
name="err1"
path="src/Err1.rs"


[[bin]]
name="err2"
path="src/Err2.rs"

[[bin]]
name="err3"
path="src/Err3.rs"

[[bin]]
name="err4"
path="src/Err4.rs"

[[bin]]
name="opt1"
path="src/Optional1.rs"

[[bin]]
name="custom"
path="src/Custom.rs"

[[bin]]
name="mod1"
path="src/Module1.rs"

[[bin]]
name="mod2"
path="src/Module2.rs"